using System.IO;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Hoi4ModOverlay.Models;

namespace Hoi4ModOverlay.Services;

public sealed class ModSummaryEnrichmentService
{
    private static readonly HttpClient Http = CreateHttpClient();
    private readonly string _generatedSummaryPath = Path.Combine(AppContext.BaseDirectory, "data", "generated_summaries.zh-CN.json");

    public async Task<bool> EnrichMissingAsync(IEnumerable<ModInfo> mods, CancellationToken cancellationToken = default)
    {
        var missing = mods.Where(mod => !mod.HasSummary).ToArray();
        if (missing.Length == 0)
        {
            return false;
        }

        var generated = LoadGenerated();
        var changed = false;

        foreach (var mod in missing)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var key = SummaryKeyFor(mod.WorkshopId, mod.Name);
            if (generated.ContainsKey(key))
            {
                continue;
            }

            ModSummaryRecord? record;
            if (IsSteamWorkshopId(mod.WorkshopId))
            {
                // Workshop pages describe the mod itself. Local localisation files may contain
                // unrelated event/decision text, so use Steam as the primary overview source.
                record = await TryBuildFromSteamAsync(mod, cancellationToken)
                         ?? TryBuildFromLocalContent(mod);
            }
            else
            {
                record = TryBuildFromLocalContent(mod);
            }

            if (record is null)
            {
                continue;
            }

            generated[key] = record;
            if (IsSteamWorkshopId(mod.WorkshopId))
            {
                generated[mod.WorkshopId] = record;
            }
            changed = true;
        }

        if (changed)
        {
            SaveGenerated(generated);
        }

        return changed;
    }

    internal static string SummaryKeyFor(string? workshopId, string name)
    {
        if (IsSteamWorkshopId(workshopId))
        {
            return workshopId!;
        }

        var normalized = Regex.Replace(name.Trim().ToLowerInvariant(), @"\s+", " ");
        return $"name:{normalized}";
    }

    internal static bool IsSteamWorkshopId(string? value)
    {
        return ulong.TryParse(value, out var id) && id >= 1_000_000;
    }

    private static HttpClient CreateHttpClient()
    {
        var client = new HttpClient { Timeout = TimeSpan.FromSeconds(12) };
        client.DefaultRequestHeaders.UserAgent.ParseAdd("HOI4-Mod-Overlay/1.0");
        return client;
    }

    private ModSummaryRecord? TryBuildFromLocalContent(ModInfo mod)
    {
        var contentPath = mod.ContentPath;
        if (string.IsNullOrWhiteSpace(contentPath) || !Directory.Exists(contentPath))
        {
            return null;
        }

        var chinese = TryReadChineseLocalisation(contentPath);
        if (!string.IsNullOrWhiteSpace(chinese))
        {
            return new ModSummaryRecord
            {
                Summary = BuildShortSummary(chinese),
                Detail = TrimTo(chinese, 720),
                Source = contentPath,
                AutoGenerated = true
            };
        }

        var readme = TryReadLocalDocumentation(contentPath);
        if (!string.IsNullOrWhiteSpace(readme) && ContainsChinese(readme))
        {
            return new ModSummaryRecord
            {
                Summary = BuildShortSummary(readme),
                Detail = TrimTo(readme, 720),
                Source = contentPath,
                AutoGenerated = true
            };
        }

        return null;
    }

    private async Task<ModSummaryRecord?> TryBuildFromSteamAsync(ModInfo mod, CancellationToken cancellationToken)
    {
        try
        {
            using var content = new FormUrlEncodedContent(new Dictionary<string, string>
            {
                ["itemcount"] = "1",
                ["publishedfileids[0]"] = mod.WorkshopId
            });
            using var response = await Http.PostAsync(
                "https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/",
                content,
                cancellationToken);
            response.EnsureSuccessStatusCode();

            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            using var doc = await JsonDocument.ParseAsync(stream, cancellationToken: cancellationToken);
            var details = doc.RootElement.GetProperty("response").GetProperty("publishedfiledetails");
            if (details.GetArrayLength() == 0)
            {
                return null;
            }

            var detail = details[0];
            if (!detail.TryGetProperty("description", out var descriptionElement))
            {
                return null;
            }

            var sourceText = CleanSteamText(descriptionElement.GetString());
            if (sourceText.Length < 12)
            {
                return null;
            }

            var selected = SelectFunctionalText(sourceText);
            var chinese = ContainsChinese(selected)
                ? selected
                : await TranslateToChineseAsync(selected, cancellationToken) ?? selected;

            var source = $"https://steamcommunity.com/sharedfiles/filedetails/?id={mod.WorkshopId}";
            return new ModSummaryRecord
            {
                Summary = BuildShortSummary(chinese),
                Detail = TrimTo(chinese, 900),
                Source = source,
                AutoGenerated = true
            };
        }
        catch
        {
            return null;
        }
    }

    private static string? TryReadChineseLocalisation(string contentPath)
    {
        try
        {
            var root = Path.Combine(contentPath, "localisation", "simp_chinese");
            if (!Directory.Exists(root))
            {
                return null;
            }

            string? best = null;
            var bestScore = 0;
            foreach (var file in Directory.EnumerateFiles(root, "*.yml", SearchOption.AllDirectories).Take(80))
            {
                foreach (var line in File.ReadLines(file).Take(1200))
                {
                    var match = Regex.Match(line, "^\\s*([^#][^:]*):\\d*\\s*\\\"(.*)\\\"\\s*$", RegexOptions.CultureInvariant);
                    if (!match.Success)
                    {
                        continue;
                    }

                    var key = match.Groups[1].Value.Trim().ToLowerInvariant();
                    if (!key.Contains("desc", StringComparison.Ordinal))
                    {
                        continue;
                    }

                    var text = CleanHoi4Text(match.Groups[2].Value);
                    if (!ContainsChinese(text) || text.Length < 18)
                    {
                        continue;
                    }

                    var score = Math.Min(text.Length, 500);
                    if (key.Contains("category_desc", StringComparison.Ordinal)) score += 500;
                    else if (key.EndsWith("_desc", StringComparison.Ordinal)) score += 250;
                    if (score > bestScore)
                    {
                        bestScore = score;
                        best = text;
                    }
                }
            }

            return best;
        }
        catch
        {
            return null;
        }
    }

    private static string? TryReadLocalDocumentation(string contentPath)
    {
        try
        {
            var candidates = new List<string>();
            candidates.AddRange(Directory.EnumerateFiles(contentPath, "README*", SearchOption.TopDirectoryOnly));
            candidates.AddRange(Directory.EnumerateFiles(contentPath, "*description*", SearchOption.TopDirectoryOnly));

            var docs = Path.Combine(contentPath, "docs");
            if (Directory.Exists(docs))
            {
                candidates.AddRange(Directory.EnumerateFiles(docs, "*.md", SearchOption.TopDirectoryOnly).Take(12));
            }

            foreach (var file in candidates.Distinct(StringComparer.OrdinalIgnoreCase).Take(20))
            {
                var text = File.ReadAllText(file);
                if (text.Length > 12000) text = text[..12000];
                text = CleanDocumentationText(text);
                if (text.Length >= 30)
                {
                    return text;
                }
            }
        }
        catch
        {
            // Local documentation is only a fallback source.
        }

        return null;
    }

    private static string CleanHoi4Text(string value)
    {
        var text = value.Replace("\\n", " ");
        text = Regex.Replace(text, "§.", string.Empty);
        text = Regex.Replace(text, @"\[[^\]]+\]", string.Empty);
        text = Regex.Replace(text, @"£[A-Za-z0-9_]+", string.Empty);
        text = Regex.Replace(text, @"\?[^\s]+", string.Empty);
        return CollapseWhitespace(text);
    }

    private static string CleanSteamText(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return string.Empty;
        var text = WebUtility.HtmlDecode(value);
        text = Regex.Replace(text, @"\[/?[^\]]+\]", " ");
        text = Regex.Replace(text, @"https?://\S+", " ");
        text = text.Replace("\r", " ").Replace("\n", " ");
        return CollapseWhitespace(text);
    }

    private static string CleanDocumentationText(string value)
    {
        var text = Regex.Replace(value, @"```[\s\S]*?```", " ");
        text = Regex.Replace(text, @"^\s{0,3}#{1,6}\s*", string.Empty, RegexOptions.Multiline);
        text = Regex.Replace(text, @"\[(.*?)\]\([^\)]*\)", "$1");
        text = Regex.Replace(text, @"[`*_>|-]", " ");
        return CollapseWhitespace(text);
    }

    private static string SelectFunctionalText(string text)
    {
        if (text.Length <= 1800) return text;
        return text[..1800];
    }

    private static async Task<string?> TranslateToChineseAsync(string text, CancellationToken cancellationToken)
    {
        try
        {
            var input = TrimTo(text, 2600);
            var url = "https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=zh-CN&dt=t&q=" + Uri.EscapeDataString(input);
            using var response = await Http.GetAsync(url, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            using var doc = await JsonDocument.ParseAsync(stream, cancellationToken: cancellationToken);

            var sb = new StringBuilder();
            foreach (var segment in doc.RootElement[0].EnumerateArray())
            {
                if (segment.ValueKind == JsonValueKind.Array && segment.GetArrayLength() > 0 && segment[0].ValueKind == JsonValueKind.String)
                {
                    sb.Append(segment[0].GetString());
                }
            }

            var translated = CollapseWhitespace(sb.ToString());
            return translated.Length >= 8 ? translated : null;
        }
        catch
        {
            return null;
        }
    }

    private Dictionary<string, ModSummaryRecord> LoadGenerated()
    {
        try
        {
            if (!File.Exists(_generatedSummaryPath))
            {
                return new Dictionary<string, ModSummaryRecord>(StringComparer.OrdinalIgnoreCase);
            }

            return JsonSerializer.Deserialize<Dictionary<string, ModSummaryRecord>>(
                       File.ReadAllText(_generatedSummaryPath),
                       new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
                   ?? new Dictionary<string, ModSummaryRecord>(StringComparer.OrdinalIgnoreCase);
        }
        catch
        {
            return new Dictionary<string, ModSummaryRecord>(StringComparer.OrdinalIgnoreCase);
        }
    }

    private void SaveGenerated(Dictionary<string, ModSummaryRecord> generated)
    {
        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(_generatedSummaryPath)!);
            var json = JsonSerializer.Serialize(generated, new JsonSerializerOptions { WriteIndented = true });
            var temp = _generatedSummaryPath + ".tmp";
            File.WriteAllText(temp, json);
            File.Move(temp, _generatedSummaryPath, true);
        }
        catch
        {
            // Failure to cache must not make the overlay unusable.
        }
    }

    private static string BuildShortSummary(string text)
    {
        var clean = CollapseWhitespace(text);
        var sentence = Regex.Match(clean, @"^.{20,220}?[。！？!?](?:\s|$)");
        if (sentence.Success)
        {
            return sentence.Value.Trim();
        }

        return TrimTo(clean, 180);
    }

    private static string TrimTo(string text, int maxLength)
    {
        var clean = CollapseWhitespace(text);
        return clean.Length <= maxLength ? clean : clean[..maxLength].TrimEnd() + "…";
    }

    private static bool ContainsChinese(string value)
    {
        return value.Any(ch => ch is >= '\u3400' and <= '\u9fff');
    }

    private static string CollapseWhitespace(string value)
    {
        return Regex.Replace(value, @"\s+", " ").Trim();
    }
}
