namespace Hoi4ModOverlay.Models;

public sealed class ModSummaryRecord
{
    public required string Summary { get; init; }
    public string? Detail { get; init; }
    public string? Source { get; init; }
    public bool AutoGenerated { get; init; }
}
